name: Build Nanos Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies (QEMU)
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86

      - name: Install ops (NanoVMs)
        run: |
          curl -L https://ops.city/get.sh | sh

      - name: Add ops to PATH
        run: |
          echo "$HOME/.ops/bin" >> $GITHUB_PATH

      - name: Verify ops installation
        run: |
          ops version

      - name: Download & extract Payara (dynamic dir)
        run: |
          mkdir -p nanos-root
          mkdir -p payara-tmp
      
          wget -O payara.zip https://nexus.payara.fish/repository/payara-community/fish/payara/distributions/payara/7.2025.2/payara-7.2025.2.zip
          unzip -q payara.zip -d payara-tmp
      
          # move *content* of first-level directory into nanos-root
          PAYARA_DIR=$(find payara-tmp -mindepth 1 -maxdepth 1 -type d | head -n 1)
          mv "$PAYARA_DIR"/* nanos-root/
      
      - name: Create /etc/hosts for Nanos      
        run: |
          mkdir -p nanos-root/payara7/etc
          cat > nanos-root/payara7/etc/hosts <<'EOF'
                127.0.0.1 localhost
                10.0.2.15 10-0-2-15
                EOF
    
      - name: Load
        run: |          
          cd nanos-root/payara7
          ops image create --imagename payara --package AngeloRubens/AzulJREx64Linux:25.0.1 --nightly -c ../../config.json
